version: '3.8'

services:
  ambev.developerevaluation.webapi:
    container_name: ambev_developer_evaluation_webapi
    image: ${DOCKER_REGISTRY-}ambevdeveloperevaluationwebapi
    build:
      context: .
      dockerfile: src/Ambev.DeveloperEvaluation.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=Host=ambev.developerevaluation.database;Database=DeveloperEvaluation;Username=developer;Password=ev@luAt10n;
    ports:
      - "5050:8080"
      - "5051:8081"
    depends_on:
    - ambev.developerevaluation.database
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
    - ambev-sale-developer-network

  ambev.developerevaluation.database:
    container_name: ambev_developer_evaluation_database
    image: postgres:17.5
    environment:
      POSTGRES_DB: DeveloperEvaluation
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: ev@luAt10n
    ports:
      - "5500:5432"
    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - ambev-sale-developer-network

networks: 
    ambev-sale-developer-network:
        driver: bridge